[package]
name = "bogosort"
version = "0.1.0"
authors = ["mxrr <datmixor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
stopwatch = "0.0.7"
